# SPDX-License-Identifier: ISC
# MT7925 submodule Makefile for out-of-tree DKMS build

obj-m += mt7925-common.o
obj-m += mt7925e.o

mt7925-common-y := mac.o mcu.o main.o init.o debugfs.o
mt7925e-y := pci.o pci_mac.o pci_mcu.o
